# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-03 01:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udoco', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='official',
            name='game_history',
            field=models.URLField(blank=True),
        ),
    ]
