# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-03 22:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udoco', '0002_auto_20160503_0107'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='league name')),
                ('abbreviation', models.CharField(max_length=5, verbose_name='league abbreviation')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('schedulers', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
