# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-03 22:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udoco', '0003_league'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='schedulers',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
