# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-04 01:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udoco', '0004_auto_20160503_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='schedulers',
            field=models.ManyToManyField(blank=True, related_name='scheduling', to=settings.AUTH_USER_MODEL),
        ),
    ]
