# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-04 01:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('udoco', '0005_auto_20160504_0113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024, verbose_name='title')),
                ('start', models.DateTimeField(verbose_name='game start')),
                ('end', models.DateTimeField(verbose_name='game end')),
                ('location', models.CharField(max_length=1024, verbose_name='address')),
                ('association', models.PositiveIntegerField(choices=[(0, b'WFTDA'), (1, b'MRDA'), (2, b'JRDA'), (99, b'OTHER')])),
                ('game_type', models.PositiveIntegerField(choices=[(0, b'SANCTIONED'), (1, b'REGULATION'), (99, b'OTHER')])),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='udoco.League')),
            ],
        ),
    ]
