# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-05 00:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('udoco', '0007_auto_20160504_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='official',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL),
        ),
    ]
