# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-05 00:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('udoco', '0008_auto_20160505_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='udoco.Game'),
        ),
    ]
