# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 23:57
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udoco', '0009_auto_20160505_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='official',
            name='emergency_contact_name',
            field=models.CharField(default='', max_length=256, verbose_name='name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='official',
            name='emergency_contact_number',
            field=models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AddField(
            model_name='official',
            name='phone_number',
            field=models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
