# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-24 03:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('udoco', '0011_roster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roster',
            name='alt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alt_games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='roster',
            name='ipr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ipr_games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='roster',
            name='opr1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opr1_games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='roster',
            name='opr2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opr2_games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='roster',
            name='opr3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opr3_games', to=settings.AUTH_USER_MODEL),
        ),
    ]
