# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-24 04:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('udoco', '0012_auto_20160824_0357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roster',
            name='id',
        ),
        migrations.AlterField(
            model_name='roster',
            name='game',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='udoco.Game'),
        ),
    ]
