# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-05 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udoco', '0013_auto_20160824_0403'),
    ]

    operations = [
        migrations.AddField(
            model_name='official',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='/avatars/'),
        ),
    ]
