# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-19 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udoco', '0016_auto_20160910_0530'),
    ]

    operations = [
        migrations.AddField(
            model_name='official',
            name='league_affiliation',
            field=models.CharField(blank=True, max_length=256, verbose_name='affiliation'),
        ),
        migrations.AddField(
            model_name='official',
            name='official_type',
            field=models.PositiveIntegerField(choices=[(0, 'All'), (1, 'Skating'), (2, 'Nonskating')], default=0),
        ),
    ]
