# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-19 04:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('udoco', '0017_auto_20160919_0245'),
    ]

    operations = [
        migrations.AddField(
            model_name='roster',
            name='pt1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pt1_games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roster',
            name='pt2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pt2_games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='application',
            name='nso_first_choice',
            field=models.PositiveIntegerField(choices=[(0, 'Jam Timer'), (1, 'Score Keeper'), (2, 'Penalty Box Manager'), (3, 'Penalty Box Timer'), (4, 'Penalty Tracker'), (5, 'Penalty Wrangler'), (6, 'Inside Whiteboard'), (7, 'Lineup Tracker'), (8, 'Scoreboard Operator')]),
        ),
        migrations.AlterField(
            model_name='application',
            name='nso_second_choice',
            field=models.PositiveIntegerField(choices=[(0, 'Jam Timer'), (1, 'Score Keeper'), (2, 'Penalty Box Manager'), (3, 'Penalty Box Timer'), (4, 'Penalty Tracker'), (5, 'Penalty Wrangler'), (6, 'Inside Whiteboard'), (7, 'Lineup Tracker'), (8, 'Scoreboard Operator')]),
        ),
        migrations.AlterField(
            model_name='application',
            name='nso_third_choice',
            field=models.PositiveIntegerField(choices=[(0, 'Jam Timer'), (1, 'Score Keeper'), (2, 'Penalty Box Manager'), (3, 'Penalty Box Timer'), (4, 'Penalty Tracker'), (5, 'Penalty Wrangler'), (6, 'Inside Whiteboard'), (7, 'Lineup Tracker'), (8, 'Scoreboard Operator')]),
        ),
    ]
