# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-20 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udoco', '0018_auto_20160919_0411'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='email_template',
            field=models.TextField(blank=True),
        ),
    ]
