# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-20 04:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('udoco', '0019_league_email_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roster',
            name='hr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hr_games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='roster',
            name='jr1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jr1_games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='roster',
            name='jr2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jr2_games', to=settings.AUTH_USER_MODEL),
        ),
    ]
