# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-20 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udoco', '0020_auto_20160920_0425'),
    ]

    operations = [
        migrations.AddField(
            model_name='roster',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
