# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-20 16:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('udoco', '0021_roster_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='roster',
            name='so',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='so_games', to=settings.AUTH_USER_MODEL),
        ),
    ]
