# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-21 02:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('udoco', '0022_roster_so'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roster',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='udoco.Game'),
        ),
    ]
