# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-24 02:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('udoco', '0023_auto_20160921_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roster',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='rosters', serialize=False, to='udoco.Game'),
        ),
    ]
