# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-24 02:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('udoco', '0024_auto_20160924_0253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roster',
            name='alt',
        ),
        migrations.RemoveField(
            model_name='roster',
            name='game',
        ),
        migrations.RemoveField(
            model_name='roster',
            name='hr',
        ),
        migrations.RemoveField(
            model_name='roster',
            name='ipr',
        ),
        migrations.RemoveField(
            model_name='roster',
            name='iwb',
        ),
        migrations.RemoveField(
            model_name='roster',
            name='jr1',
        ),
        migrations.RemoveField(
            model_name='roster',
            name='jr2',
        ),
        migrations.RemoveField(
            model_name='roster',
            name='jt',
        ),
        migrations.RemoveField(
            model_name='roster',
            name='lt1',
        ),
        migrations.RemoveField(
            model_name='roster',
            name='lt2',
        ),
        migrations.RemoveField(
            model_name='roster',
            name='opr1',
        ),
        migrations.RemoveField(
            model_name='roster',
            name='opr2',
        ),
        migrations.RemoveField(
            model_name='roster',
            name='opr3',
        ),
        migrations.RemoveField(
            model_name='roster',
            name='pbm',
        ),
        migrations.RemoveField(
            model_name='roster',
            name='pbt1',
        ),
        migrations.RemoveField(
            model_name='roster',
            name='pbt2',
        ),
        migrations.RemoveField(
            model_name='roster',
            name='pt1',
        ),
        migrations.RemoveField(
            model_name='roster',
            name='pt2',
        ),
        migrations.RemoveField(
            model_name='roster',
            name='pw',
        ),
        migrations.RemoveField(
            model_name='roster',
            name='sk1',
        ),
        migrations.RemoveField(
            model_name='roster',
            name='sk2',
        ),
        migrations.RemoveField(
            model_name='roster',
            name='so',
        ),
        migrations.DeleteModel(
            name='Roster',
        ),
    ]
