# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-24 02:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('udoco', '0025_auto_20160924_0256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete', models.BooleanField(default=False)),
                ('alt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alt_games', to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rosters', to='udoco.Game')),
                ('hr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hr_games', to=settings.AUTH_USER_MODEL)),
                ('ipr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ipr_games', to=settings.AUTH_USER_MODEL)),
                ('iwb', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='iwb_games', to=settings.AUTH_USER_MODEL)),
                ('jr1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jr1_games', to=settings.AUTH_USER_MODEL)),
                ('jr2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jr2_games', to=settings.AUTH_USER_MODEL)),
                ('jt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jt_games', to=settings.AUTH_USER_MODEL)),
                ('lt1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lt1_games', to=settings.AUTH_USER_MODEL)),
                ('lt2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lt2_games', to=settings.AUTH_USER_MODEL)),
                ('opr1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opr1_games', to=settings.AUTH_USER_MODEL)),
                ('opr2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opr2_games', to=settings.AUTH_USER_MODEL)),
                ('opr3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opr3_games', to=settings.AUTH_USER_MODEL)),
                ('pbm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pbm_games', to=settings.AUTH_USER_MODEL)),
                ('pbt1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pbt1_games', to=settings.AUTH_USER_MODEL)),
                ('pbt2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pbt2_games', to=settings.AUTH_USER_MODEL)),
                ('pt1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pt1_games', to=settings.AUTH_USER_MODEL)),
                ('pt2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pt2_games', to=settings.AUTH_USER_MODEL)),
                ('pw', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pw_games', to=settings.AUTH_USER_MODEL)),
                ('sk1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sk1_games', to=settings.AUTH_USER_MODEL)),
                ('sk2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sk2_games', to=settings.AUTH_USER_MODEL)),
                ('so', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='so_games', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
