# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-25 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udoco', '0026_roster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roster',
            name='complete',
        ),
        migrations.AddField(
            model_name='game',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
