# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-27 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udoco', '0027_auto_20160925_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='so_first_choice',
            field=models.PositiveIntegerField(choices=[(0, 'Head Ref'), (1, 'Inside Pack Ref'), (2, 'Jam Ref'), (3, 'Outside Pack Ref'), (4, 'Alt')]),
        ),
        migrations.AlterField(
            model_name='application',
            name='so_second_choice',
            field=models.PositiveIntegerField(choices=[(0, 'Head Ref'), (1, 'Inside Pack Ref'), (2, 'Jam Ref'), (3, 'Outside Pack Ref'), (4, 'Alt')]),
        ),
        migrations.AlterField(
            model_name='application',
            name='so_third_choice',
            field=models.PositiveIntegerField(choices=[(0, 'Head Ref'), (1, 'Inside Pack Ref'), (2, 'Jam Ref'), (3, 'Outside Pack Ref'), (4, 'Alt')]),
        ),
    ]
