# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-13 06:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('udoco', '0029_applicationentry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationentry',
            old_name='so_first_choice',
            new_name='preference',
        ),
    ]
