# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-13 06:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('udoco', '0030_auto_20170213_0625'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationentry',
            old_name='game',
            new_name='event',
        ),
    ]
