# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-01 00:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('udoco', '0032_application_to_entry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roster',
            options={'ordering': ['id']},
        ),
    ]
