# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-01 03:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('udoco', '0033_auto_20170301_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='roster',
            name='hnso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hnso_games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roster',
            name='nsoalt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nsoalt_games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roster',
            name='ptimer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ptimer_games', to=settings.AUTH_USER_MODEL),
        ),
    ]
