# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-02 17:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('udoco', '0034_auto_20170301_0303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('derby_name', models.CharField(max_length=265, verbose_name='Derby name')),
                ('real_name', models.CharField(max_length=265, verbose_name='Derby name')),
            ],
        ),
        migrations.CreateModel(
            name='LoserApplicationEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('preference', models.PositiveIntegerField(choices=[(0, 'Head Ref'), (1, 'Inside Pack Ref'), (2, 'Jam Ref'), (3, 'Outside Pack Ref'), (4, 'Alt'), (5, 'Head Nso'), (6, 'Penalty Tracker'), (7, 'Penalty Wrangler'), (8, 'Inside Whiteboard'), (9, 'Jam Timer'), (10, 'Score Keeper'), (11, 'Scoreboard Operator'), (12, 'Penalty Box Manager'), (13, 'Penalty Box Timer'), (14, 'Lineup Tracker'), (15, 'Alt1'), (16, 'Alt2')])),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loserapplicationentries', to='udoco.Game')),
                ('official', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicationentries', to='udoco.Loser')),
            ],
        ),
    ]
