# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-02 18:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('udoco', '0035_loser_loserapplicationentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loser',
            name='real_name',
        ),
    ]
