# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-02 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udoco', '0036_remove_loser_real_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='loser',
            name='email_address',
            field=models.EmailField(default='', max_length=254, unique=True, verbose_name='Email address'),
            preserve_default=False,
        ),
    ]
