# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-02 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udoco', '0037_loser_email_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loser',
            name='email_address',
            field=models.EmailField(max_length=254, verbose_name='Email address'),
        ),
    ]
