# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-01 19:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('udoco', '0041_auto_20171126_0449'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='official',
            options={'ordering': ['display_name']},
        ),
        migrations.RemoveField(
            model_name='game',
            name='end',
        ),
    ]
