# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-01 20:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('udoco', '0042_auto_20171201_1937'),
    ]

    operations = [
        migrations.RenameField('ApplicationEntry', 'event', 'game'),
        migrations.RenameField('LoserApplicationEntry', 'event', 'game'),
    ]
