# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-01 20:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('udoco', '0043_auto_20171201_2009'),
    ]

    operations = [
        migrations.RenameField('Loser', 'email_address', 'email'),
    ]
