# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-14 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udoco', '0044_auto_20171201_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='notes',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='loser',
            name='notes',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
