# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-15 02:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('udoco', '0046_auto_20180114_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='game',
        ),
        migrations.RemoveField(
            model_name='application',
            name='official',
        ),
        migrations.DeleteModel(
            name='Application',
        ),
    ]
