# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-31 05:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('udoco', '0047_auto_20180114_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roster',
            name='alt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alt_games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='roster',
            name='alt_x',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='udoco.Loser'),
        ),
        migrations.AlterField(
            model_name='roster',
            name='hnso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hnso_games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='roster',
            name='hnso_x',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='udoco.Loser'),
        ),
        migrations.AlterField(
            model_name='roster',
            name='hr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='roster',
            name='hr_x',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='udoco.Loser'),
        ),
        migrations.AlterField(
            model_name='roster',
            name='ipr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ipr_games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='roster',
            name='ipr_x',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='udoco.Loser'),
        ),
        migrations.AlterField(
            model_name='roster',
            name='iwb',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iwb_games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='roster',
            name='iwb_x',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='udoco.Loser'),
        ),
        migrations.AlterField(
            model_name='roster',
            name='jr1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jr1_games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='roster',
            name='jr1_x',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='udoco.Loser'),
        ),
        migrations.AlterField(
            model_name='roster',
            name='jr2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jr2_games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='roster',
            name='jr2_x',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='udoco.Loser'),
        ),
        migrations.AlterField(
            model_name='roster',
            name='jt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jt_games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='roster',
            name='jt_x',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='udoco.Loser'),
        ),
        migrations.AlterField(
            model_name='roster',
            name='lt1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lt1_games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='roster',
            name='lt1_x',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='udoco.Loser'),
        ),
        migrations.AlterField(
            model_name='roster',
            name='lt2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lt2_games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='roster',
            name='lt2_x',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='udoco.Loser'),
        ),
        migrations.AlterField(
            model_name='roster',
            name='nsoalt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nsoalt_games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='roster',
            name='nsoalt_x',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='udoco.Loser'),
        ),
        migrations.AlterField(
            model_name='roster',
            name='opr1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opr1_games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='roster',
            name='opr1_x',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='udoco.Loser'),
        ),
        migrations.AlterField(
            model_name='roster',
            name='opr2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opr2_games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='roster',
            name='opr2_x',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='udoco.Loser'),
        ),
        migrations.AlterField(
            model_name='roster',
            name='opr3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opr3_games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='roster',
            name='opr3_x',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='udoco.Loser'),
        ),
        migrations.AlterField(
            model_name='roster',
            name='pbm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pbm_games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='roster',
            name='pbm_x',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='udoco.Loser'),
        ),
        migrations.AlterField(
            model_name='roster',
            name='pbt1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pbt1_games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='roster',
            name='pbt1_x',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='udoco.Loser'),
        ),
        migrations.AlterField(
            model_name='roster',
            name='pbt2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pbt2_games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='roster',
            name='pbt2_x',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='udoco.Loser'),
        ),
        migrations.AlterField(
            model_name='roster',
            name='pt1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pt1_games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='roster',
            name='pt1_x',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='udoco.Loser'),
        ),
        migrations.AlterField(
            model_name='roster',
            name='pt2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pt2_games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='roster',
            name='pt2_x',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='udoco.Loser'),
        ),
        migrations.AlterField(
            model_name='roster',
            name='ptimer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ptimer_games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='roster',
            name='ptimer_x',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='udoco.Loser'),
        ),
        migrations.AlterField(
            model_name='roster',
            name='pw',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pw_games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='roster',
            name='pw_x',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='udoco.Loser'),
        ),
        migrations.AlterField(
            model_name='roster',
            name='sk1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sk1_games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='roster',
            name='sk1_x',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='udoco.Loser'),
        ),
        migrations.AlterField(
            model_name='roster',
            name='sk2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sk2_games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='roster',
            name='sk2_x',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='udoco.Loser'),
        ),
        migrations.AlterField(
            model_name='roster',
            name='so',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='so_games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='roster',
            name='so_x',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='udoco.Loser'),
        ),
    ]
